{
 "title": "FastAPI vs Golang",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"fastapi\"} / 1024 / 1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "process_resident_memory_bytes{job=\"golang\"} / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"fastapi\"}[1m]) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"golang\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p(50)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"fastapi\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"golang\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p(95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"fastapi\"}[1m])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_request_duration_seconds_bucket{service=\"golang\"}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "description": "total successful requests per second.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service=\"fastapi\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(http_requests_total{service=\"golang\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{service=\"fastapi\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(http_requests_total{service=\"golang\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}