apiVersion: batch/v1
kind: Job
metadata:
  name: k6-fastapi
  namespace: poc-compare
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:0.47.0
          env:
            - name: TARGET
              value: "http://fastapi.poc-compare.svc.cluster.local/cpu"
          args: ["run", "/load.js"]
          volumeMounts:
            - name: script
              mountPath: /load.js
              subPath: load.js
      volumes:
        - name: script
          configMap:
            name: k6-script
  backoffLimit: 0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6-golang
  namespace: poc-compare
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: k6
          image: grafana/k6:0.47.0
          env:
            - name: TARGET
              value: "http://golang.poc-compare.svc.cluster.local/cpu"
          args: ["run", "/load.js"]
          volumeMounts:
            - name: script
              mountPath: /load.js
              subPath: load.js
      volumes:
        - name: script
          configMap:
            name: k6-script
  backoffLimit: 0
